#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    
    #if len(sys.argv) != 2:
    #    print("Usage: ./tweets @screen_name")
    #    return 1

    screen_name = sys.argv[1]

    if not screen_name:
        print("did not find the name")
        return 2

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get screen_name's tweets
    tweets = helpers.get_user_timeline(screen_name)
    
    score=0
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score>0:
            print(colored("{} {}".format(score,tweet),"green"))
        elif score<0:
            print(colored("{} {}".format(score,tweet),"red"))
        else:
            print(colored("{} {}".format(score,tweet),"yellow"))

    


if __name__ == "__main__":
    main()
